- vtex.env
enable node_modules cache for faster builds
> chore: Enable node_modules cache

- CHANGELOG.md
- cypress/integration/analytics.test.js
- src/components/ui/QuantitySelector/QuantitySelector.tsx
Add tests to cart analytics
This PR tests if events are fired when users decrease or increase the quantity of a product on minicart (`add_to_cart` and `remove_from_cart`)
Run Cypress hahah
<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>
> chore: add tests to cart analytics

- CHANGELOG.md
- src/components/ui/Checkbox/Checkbox.tsx
Adjusts CSS Modules class on `Checkbox` component.
> Chore: Checkbox CSS Modules class

- CHANGELOG.md
- public/robots.txt
Fix lighthouse complaining about robots.txt.
> fix: lighthouse complaining about robots.txt

- .storybook/storybook.css
- src/components/product/OutOfStock/OutOfStock.stories.mdx
- src/components/sections/BannerText/BannerText.stories.mdx
- src/components/sections/Incentives/Incentives.stories.mdx
- src/components/ui/Checkbox/Checkbox.stories.mdx
- src/components/ui/QuantitySelector/QuantitySelector.stories.mdx
- src/components/ui/Toast/toast.module.scss
- src/components/ui/Toggle/Toggle.stories.mdx
- src/stories/colors.stories.mdx
- src/stories/icons.stories.mdx
- src/stories/theming.stories.mdx
- src/stories/typography.stories.mdx
Cherry-pick from Gatsby project: https://github.com/vtex-sites/gatsby.store/pull/79
Improves Storybook titles and section spacing.
> Fix: Improves Storybook titles

- CHANGELOG.md
- src/components/ui/QuantitySelector/QuantitySelector.stories.mdx
- src/components/ui/QuantitySelector/QuantitySelector.tsx
Signed-off-by: Arthur Andrade <arthurfelandrade@gmail.com>
Change Storybook prop descriptions for `QuantitySelector` component
> feat: Fix document in QuantitySelector

- .storybook/components/TokenDivider.tsx
- .storybook/storybook.css
- CHANGELOG.md
Attempts to improve the row styles. It looked a bit confusing because we were using alternate colors for the rows, and we also had some empty rows for the dividers.
**This change will only be applied to the docs already using `TokenDivider`.
We will be updating all the component's docs gradually.
|Before|
|-|
|After|
|-|
Check on the [preview](https://vercel.com/faststore/nextjs-store-storybook/6GBsUfQJeriYBnRNjHK8k9wuJxNX): all the rows should have white background color applied and the dividers, light gray background color.
**This change will only be applied to the docs already using `TokenDivider`.
We will be updating all the component's docs gradually.
<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>
<em>Extra tip: add references to …
> Chore: Improves rows and dividers on storybook

- CHANGELOG.md
This PR updates the CHANGELOG so we can have a new release, following [Base Store Release - May 2022 | FastStore](https://www.faststore.dev/releases/2022/06/03/basestore)
> Updates CHANGELOG.md with 22.23.0.beta

- CHANGELOG.md
- src/components/ui/PriceRange/PriceRange.stories.mdx
- src/components/ui/PriceRange/PriceRange.tsx
- src/components/ui/PriceRange/price-range.module.scss
- yarn.lock
Adds priceRange component from `@faststore/ui` to the starter. This PR serves for splitting responsibility from #121 so it's more clear this component's implementation
> feat: PriceRange component

- CHANGELOG.md
- src/Layout.tsx
- src/sdk/ui/Provider.tsx
As title says, this PR fixes a sonarqube warning
> fix: Sonarqube warning

- CHANGELOG.md
- src/components/search/Filter/Facets.stories.mdx
- src/components/search/Filter/facets.module.scss
Aims to adjust the tokens' names in `faces.module.scss` file.
**Changelog**
> Chore: Adjusts facets tokens

- CHANGELOG.md
This PR updates the CHANGELOG to bump the version to 22.26.0.beta
> Updates CHANGELOG.md with 22.26.0.beta

- package.json
- yarn.lock
This PR Upgrades next.JS to the latest version of the framework
> chore: Upgrade Next.JS

- src/components/sections/BannerText/BannerText.stories.mdx
- src/pages/index.tsx
Just improving the BannerText content example to avoid misleading.
Replaced `Receive our news and promotions in advance. Enjoy and get 10% off on your first purchase.`
with `The sun has set on our Summer Sale! Save up to 50% off. Don't miss out!`
Everything should work fine. Only changed the text example.
> chore: Updates `BannerText` content example

- src/components/sections/Hero/hero.scss
- src/stories/typography.stories.mdx
- src/styles/global/tokens.scss
Updates all the breakpoint tokens to follow the same suffix pattern: `-mobile` / `-tablet` / `-notebook` / `-desktop` 
Some tokens were still using `-mob` and `-desk` suffix. Now should be updated.
No visual changes were applied. Everything should work as before.
> chore: Renames/Updates breakpoints tokens

- src/components/sections/Hero/Hero.tsx
Follow-up of https://github.com/vtex-sites/nextjs.store/pull/217
Adds props description added https://github.com/vtex-sites/gatsby.store/pull/194
- Adds props description
Check on the storybook [preview](https://nextjs-store-storybook-git-chore-follow-up-her-37bbe8-faststore.vercel.app/?path=/docs/organisms-hero--usage).
> chore: Adds props description - Hero documentation (Storybook) 

- package.json
- src/pages/api/graphql.ts
- src/server/index.ts
- yarn.lock
This PR adds `@cacheControl` directive to graphql schema. After this PR, searches and dynamic data will also start being built incrementally, meaning more performance. More info at: https://github.com/vtex/faststore/pull/1473
> feat: add @cacheControl directive to GraphQL schema

- package.json
- yarn.lock
This is a fix for this issue: https://github.com/vtex/faststore/pull/1475
> fix: Wrong sku being returned for slug

- package.json
- yarn.lock
Upgrades NextJS version
Nothing should have changed
> chore: Uprgade NextJS version

- README.md
It's been some time we have some features the README says we don't. This PR upgrades just that
> docs: Update Missing Features

- src/components/cart/CartToggle/CartToggle.tsx
- src/components/common/Navbar/navbar.module.scss
Update `CartToggle` data-attr from `data-fs-button-cart` to `data-fs-cart-toggle`
Everything should look the same.
> chore: Renames CartToggle data-attr

- package.json
- yarn.lock
More info at: https://github.com/vtex/faststore/pull/1488
> fix: Bad postal code on shipping data 

- src/components/cms/RenderPageSections.tsx
This PR is a quick win adding the newsletter section to the CMS renderer
> feat: Adds newsleter section

- .release-it.json
- package.json
- yarn.lock
This PR renames this pacckage to faststore/core and add it to npm so we can improve our evergreen approach
> feat: publish @faststore/core to npm

- src/pages/index.tsx
This PR fixes https://github.com/vtex-sites/nextjs.store/issues/222
> fix: Searchbox

- package.json
- src/components/ui/Carousel/Carousel.stories.mdx
- src/components/ui/Carousel/Carousel.tsx
- src/components/ui/Carousel/carousel.module.scss
- src/components/ui/Carousel/index.ts
- yarn.lock
This PR intends to add the `Carousel` component using the refactored FastStore's `Carousel`.
This starter will use a new variant of FastStore's `Carousel` to match the design prototype.
Related to [FastStore PR #1476](https://github.com/vtex/faststore/pull/1476).
These changes can be tested through Storybook:
> feat: Adds `Carousel` component

- tsconfig.json
<em>Considering the context, what is the problem we'll solve? Where in VTEX's big picture our issue fits in? Write a tweet about the context and the problem itself.</em>
<em>Tell us the role of the new feature, or component, in its context.</em> …
> fix: next tsconfig

- package.json
- src/components/ui/Button/ButtonLink/ButtonSignIn/ButtonSignIn.tsx
- src/pages/account.tsx
- src/pages/login.tsx
- yarn.lock
Changes made at the Core at this PR:
https://github.com/vtex/faststore/pull/1653
The Order form param with the orderformId from FS will be passed at the URL at the login/my account page
Go to my account or login page 
https://user-images.githubusercontent.com/67066494/229573414-8a93067b-586b-4348-ab0a-ca562c784b2d.mp4
> chore/ add orderform param to URL

- .github/workflows/release.yml
- lighthouserc.js
- package.json
- src/pages/index.tsx
- yarn.lock
Uses `main` branch as default for the release GH workflow.
> chore: Release GH workflow with default branch to `main`
