vtex-sites/nextjs.store

CHANGELOG.md
pull_request_template.md

Added new items to the [pull_request_template.md](https://github.com/vtex-sites/nextjs.store/blob/main/pull_request_template.md) to help highlight the changes added in the `CHANGELOG.md` and Release Notes. 
> This is analogous to the [#12](https://github.com/vtex-sites/gatsby.store/pull/12) PR in `gatsby.store`.
The new items intended to help users and the team identify the changes in `gatsby.store` and keep a pattern in the `CHANGELOG.md ` update.
| Checklist Item | Before | Now |
| --------------- | -------- | ----- |
| CHANGELOG entry added | ✅ | ✅ |
| Added an entry in the `CHANGELOG.md` at the beginning of its due section. [The latest version should comes first](https://keepachangelog.com/en/1.0.0/#:~:text=The%20latest%20version%20comes%20first.).| ❌ | ✅ |
|  Added the PR number with …

Doc: Update `pull_request_template.md` checklist

---

CHANGELOG.md
src/components/regionalization/RegionalizationBar/RegionalizationBar.tsx
src/components/regionalization/RegionalizationButton/RegionalizationButton.tsx

Applies patch from https://github.com/vtex-sites/base.store/pull/495
Update Regionalization Button and Regionalization Bar to show the last postal code saved, instead of receiving a `content` prop.
1- Set a valid postal code in `RegionalizationInput` 
2- Press "enter" key
3- Push the close button.
- [Base store's PR](https://github.com/vtex-sites/base.store/pull/495)
- [Postal Code Bar's original code](https://github.com/vtex-sites/base.store/pull/424)

Feat: Update Regionalization Button and Regionalization Bar to show the postal code

---

CHANGELOG.md

It removes a duplicated "Changed" section in the Changelog, probably caused by a merge conflict.
It fixes this markdown:
It also adds links to the PRs, especially because some of them were from https://github.com/vtex-sites/base.store and not the current one.

chore: Better organize the Changelog

---

CHANGELOG.md
src/styles/global/storybook-components.scss

This PR attempts to fix storybook build removing unused import.
- Removes unused import.
- The [nextjs-store-storybook preview](https://nextjs-store-storybook-git-fix-storybook-remov-622190-faststore.vercel.app/) link should work normally.

fix: storybook build - removes unused import

---

CHANGELOG.md
next.config.js
src/components/ui/ImageGallery/ImageGallery.tsx
src/components/ui/ImageGallery/ImageGallerySelector.tsx
src/components/ui/ImageGallery/image-gallery.module.scss

This PR adds a configuration to the store that import classes as camelCase through CSS modules. This is being done because gatsby.store only import classes as camelCase and is not recommended do to in other way because it removes the tree-shaking from it.
It adds a chunk of code to `next.config.js` which changes the objected imported with CSS Modules.
Open the preview and navigate to any product. The gallery should work for mobile and desktop
https://github.com/vercel/next.js/discussions/11267
https://www.gatsbyjs.com/docs/how-to/styling/css-modules/
https://www.gatsbyjs.com/docs/how-to/styling/css-modules/

Chore: Uses camel-case classes when using CSS Modules

---

src/pages/_document.tsx

This PR aims to avoid iframe errors on Codesandbox by disabling third-party scripts on it.
It checks if the `DISABLE_3P_SCRIPTS`envvar exists and is `true`. If so, it doesn't render the `ThirdPartyScripts` component.

feat: Disable 3P scripts on Codesandbox

---

src/components/ui/InputText/InputText.stories.tsx

Removes `yarn build` warning
```
./src/components/ui/InputText/InputText.stories.tsx
4:1  Warning: Assign object to a variable before exporting as module default  import/no-anonymous-default-export
```

Fix: `InputText` story

---

CHANGELOG.md
src/components/sections/Hero/Hero.tsx
src/components/ui/Image/Image.tsx
src/components/ui/ImageGallery/ImageGallery.tsx

Try to improve the page LCP by boosting the priority for the main image.
By setting `fetchpriority` to `high` we can hint the browser to give a higher priority to our LCP images.
Use `psi-test` to compare before and after.
Page result - https://sfj-7de89f9--nextjs.preview.vtex.app/
| Metric | Mean | Standard deviation | Confidence Interval (95%) |
|--------|--------|--------|--------|
| Largest Contentful Paint (LCP) | 2221.49 | 152192.99 | [-64480.03, 68923.01] |
| Performance score | 0.839 | 0.000979 | [0.838571, 0.839429] |
Page result - https://sfj-f5d2958--nextjs.preview.vtex.app/
| Metric | Mean | Standard deviation | Confidence Interval (95%) |
|--------|--------|--------|--------|
| Largest Contentful Paint (LCP) | 1475.76 | 42521.48 | [-17160.10, 20111.61] |
| Performance score | …

Improve LCP by setting a higher fetch priority

---

CHANGELOG.md
src/components/ui/Image/Image.tsx

This PR intends to fix the warning related to `fetchPriority` prop being used with _camelCase_ and not being recognized as a DOM element's prop (`link` and `img` elements, in this case).
Build locally, open the homepage (`localhost:3000`) and check if the warning is not being displayed in the terminal anymore.

fix: Fixes `fetchPriority` prop warning

---

CHANGELOG.md
src/components/ui/Image/Image.tsx

This PR is derived from: https://github.com/vtex-sites/gatsby.store/pull/60.
This PR intends to fix global props being visible/possible for types/interfaces extended from a global interface.
In the `Image` component we declared some props for the React global interface, `HTMLAttributes`, and it affected other components. We could detect this by looking into Storybook args for any components:
With these changes, we narrowed the custom attributes only to the specific HTML tags `img` and `link`.
It can be tested by looking into the components' Storybook args and checking if any of the custom attributes (i.e, `fetchPriority`) are visible.

fix: Fixes custom attributes for img and link tags

---

src/components/ui/Image/Image.tsx

This PR intends to fix a `link` attribute typo. (`imageSizes` instead `imagesizes`)
Just try to build locally and go to the homepage, the terminal should not show the warning again.

fix: Fixes <link /> attribute typo

---

CHANGELOG.md
src/components/ui/QuantitySelector/QuantitySelector.tsx
src/components/ui/QuantitySelector/quantity-selector.module.scss
src/styles/global/components.scss
src/styles/global/storybook-components.scss

This PR uses CSS modules to import the QuantitySelector component.
Check if the `QuantitySelector` works at the cart and at the PDP.

chore: Uses CSS Modules at `QuantitySelector`

---

.storybook/components/TokenDivider.tsx
.storybook/components/TokenRow.tsx
.storybook/components/TokenTable.tsx
.storybook/components/index.ts
CHANGELOG.md
src/components/ui/QuantitySelector/QuantitySelector.stories.mdx

Signed-off-by: Arthur Andrade <arthurfelandrade@gmail.com>
This PR adds storybook documentation for QuantitySelector component.
Added the TokenTable and TokenRow components to make it easier to document tokens in the storybook.
Run storybook and see `http://localhost:6006/?path=/docs/organisms-quantityselector--quantity-selector`.

feat: Add document in QuantitySelector

---

CHANGELOG.md
src/pages/[...slug].tsx
src/pages/[slug]/p.tsx
src/server/index.ts

Fix wrong 404 during SSG
When an error occurs while fetching data needed for pages during SSG, our code threats this as a notFound. This notFound is SSG and this page will be notFound until we make a new deploy. This PR fixes this issue by throwing and error if an error occurs, making this page to be re-generated on the next request, thus generating the right page.
1. Run `yarn build && yarn serve` on your machine
2. Remove internet access (disable wifi) from your machine to simulate a communication error between the server and VTEX commerce platform
3. Enter in a PDP. You should see the 500 error page.
4. Re-enable the wifi and refresh. You should now see the correct page.

fix: Static incremental builds errors

---

CHANGELOG.md
package.json

Adds `--docs` to `storybook` script so that we can see the same storybook structure locally and on production builds.
**Changelog**

Chore: Adds `--docs` to storybook script

---

CHANGELOG.md
src/components/regionalization/RegionalizationInput/RegionalizationInput.tsx

Fix Region Input's behavior when setting zipCode
When using `Mutation.validateSession` query, `RegionalizationInput` component was passing an extra variable that was not defined on the GraphQL schema, breaking the query with the following error:
This PR addresses this issue by removing the `isValidating` variable from session.
Open the deploy preview, set the zip code and make sure the zip code is set on the UI without errors on console like so:

fix: Region Input

---

CHANGELOG.md
package.json
src/components/sections/Hero/Hero.stories.tsx
src/sdk/error/ErrorBoundary/ErrorBoundary.tsx
yarn.lock

I had tried using a new feature from React 18 called `useDeferredValue` but got a type error `Module '"react"' has no exported member 'useDeferredValue'.`. I started by [updating the type definitions from 17.x to 18.x](https://github.com/vtex-sites/nextjs.store/commit/8955ce3e42c676ffbc7eeb6d75d4d0479d6c1a97) but got another [type error with `HelmetProvider`](https://github.com/vtex-sites/nextjs.store/runs/6828783453). I was able to [remove it](https://github.com/vtex-sites/nextjs.store/commit/eb0f3f91e05a6229b4bc49bb0383625d5a55b447) as it was not really needed, but the build failed again in the next [type error in `ErrorBoundary`](https://github.com/vtex-sites/nextjs.store/runs/6828844458). Finally, after [adjusting the missing …

chore: Add support new types from React 18

---

CHANGELOG.md
src/components/regionalization/RegionalizationInput/RegionalizationInput.tsx
src/components/ui/InputText/InputText.stories.tsx
src/components/ui/InputText/InputText.tsx

This PR intends to fix the `InputText` by removing some component's local implementation, which should be the responsibility of the parent component that is rendering it.
Previously, some main attributes were being defined inside `InputText` component (e.g. `onInput` and `value`) and by doing this, parent components rendering the `InputText` had limitations using the same attributes.
The component should look the same as before. The main difference is the change of the responsibility to implement input's required attributes to the parent.
**Changelog**

fix: Transfers responsibility of `InputText`'s main attributes and callbacks to the renderer

---

CHANGELOG.md
package.json
yarn.lock

From 6.6.0. This way, it matches [Cypress version run by WebOps that was recently updated][1].
[1]: https://github.com/vtex/vtex-cicd-platform/pull/182
Run `yarn develop` and then `yarn test`.

chore: Improve integration tests by upgrading Cypress to 9.6.5

---

.github/workflows/release.yml

The release workflow was using yarn, which caused yarn.lock to prevent it from creating the version bump commit. Using bun fixes the issue.
Changes yarn commands for bun.

chore: update release workflow to use bun

---

.github/workflows/release.yml

Unfortunately, the last attempt (https://github.com/vtex-sites/nextjs.store/pull/195) [did not work](https://github.com/vtex-sites/nextjs.store/runs/7654765639?check_suite_focus=true). So it wasn't about the `bun.lockb` file not being committed...
My next attempt is to revert https://github.com/vtex-sites/nextjs.store/pull/186 so we can use `yarn` again, as we do in the [Gatsby's one](https://github.com/vtex-sites/gatsby.store/blob/8d1b1a5d668b11578784c29a9b257c78c86a1a65/.github/workflows/release.yml#L24-L29) and it's working there. I suspect [it didn't work](https://github.com/vtex-sites/nextjs.store/runs/7585048684?check_suite_focus=true) because we had an uncommitted `yarn.lock` file.
The workflow only runs when pushed to `main`, so we'll have to merge and check.
- …

fix: Attempt to fix the automated changelog update

---

src/components/common/Navbar/Navbar.tsx
src/components/search/SearchInput/SearchInput.tsx
src/components/search/SearchInput/index.tsx

This PR intends to fix the behavior when users abandon the search query and then click on the search icon again, automatically performing the search with the previous query.
Note that this behavior only happens and will be fixed in the mobile version. For the desktop version, the `SearchInput` bar persists what the user typed but without doing the automatic search.
With these changes, an imperative handle was created for the `SearchInput` ref used in the `Navbar` component, so when users cancel the search action this handler is triggered and clears the input.
Steps to reproduce (mobile version):
- Expand the search input and type anything;
- Close the search input by clicking on the left arrow icon;
- Expand the search input and the search won't be performed anymore.
Before|After
-|-
**PR …

fix: Avoids performing the search when user abandons the query [FS-243]

---

src/components/product/OutOfStock/OutOfStock.tsx

This PR intends to handle `OutOfStock` error message through `InputText` component `error` attribute.

feat: Handles `OutOfStock` error message through `InputText`'s `error` prop [FS-240]

---

src/components/ui/ShippingSimulation/ShippingSimulation.stories.mdx
src/components/ui/ShippingSimulation/shipping-simulation.module.scss
src/stories/refinements.stories.mdx
src/styles/global/tokens.scss

Removes duplication for border tokens values (`--fs-border-radius-small` and `--fs-border-radius`)
After confirming on our [Figma](https://www.figma.com/file/FGvF9W13k5UkrIq75n1oCU/Brandless-Library?node-id=3720%3A145035) file, the default one is `--fs-border-radius` is .25rem (4px).
Updates `--fs-border-radius` to  .25rem (4px)
Check on the storybook preview if the values are updated according.

chore: Renames/Updates border tokens

---

cms/sections.json

Signed-off-by: Arthur Andrade <arthurfelandrade@gmail.com>
This PR fix the config from storeframework CMS to be possible adds the IncentivesHeader and BannerText variant.
Fix sections.json config.
View the [preview](https://sfj-e9ba42b--nextjs.preview.vtex.app/office) and use the [Storeframework CMS.]( https://storeframework.myvtex.com/admin/new-cms/faststore/home/edit/ad2fd81d-a53c-4281-8d01-a4fc2f274db3/)
https://www.faststore.dev/tutorials/cms/3

fix: Fix cms config

---

.storybook/storybook.css
src/components/ui/Button/Button.stories.mdx
src/components/ui/Button/button.module.scss

This PR intends to include the old `ButtonIcon` case as a related component on Storybook.
It can be seen on `Button` story, in the _Related Components_ section (Storybook)

chore: Include `Button` with only an icon on Storybook

---

src/stories/refinements.stories.mdx
src/styles/global/tokens.scss

- Updates border tokens values to px
https://github.com/vtex-sites/nextjs.store/pull/208 Follow-up. Applying remaining [changes](https://github.com/vtex-sites/gatsby.store/pull/184/commits/543d9442749d000b61b54f8dba2294974aacd416
)
Uses `px` unit.
Check on the storybook preview if the values are updated according. 

chore: Updates border values to px

---

src/components/cms/RenderPageSections.tsx

This PR fixes the warnings below:
```
$ yarn partytown && next build
$ partytown copylib ./public/~partytown
Partytown lib copied to: /shared/project/public/~partytown
info  - Linting and checking validity of types...
./src/components/cms/RenderPageSections.tsx
13:48  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
39:69  Warning: Unexpected any. Specify a different type.  @typescript-eslint/no-explicit-any
```
I tried other techniques to avoid disabling this rule now, however, I couldn't properly type it. If you know something better, please let me know

fix build warnings

---

src/components/ui/ShippingSimulation/ShippingSimulation.stories.mdx
src/components/ui/ShippingSimulation/shipping-simulation.module.scss

Tiny PR to improve `ShippingSimulation` text tokens.
The component should look exactly the same.
|Before|After|
|-|-|
|`--fs-shipping-simulation-font-size`|`--fs-shipping-simulation-text-size`|
|`--fs-shipping-simulation-subtitle-text-size`|`--fs-shipping-simulation-subtitle-size`|
|`--fs-shipping-simulation-subtitle-text-weight`|`--fs-shipping-simulation-subtitle-weight`|
Review the updates on Storybook doc: [ShippingSimulation](https://nextjs-store-storybook-git-fix-shipping-simula-c9d67a-faststore.vercel.app/?path=/docs/features-shippingsimulation--default-story)

Fix: `ShippingSimulation` tokens

---

src/components/sections/ProductShelf/ProductShelf.tsx
src/components/sections/ProductTiles/ProductTiles.tsx

https://github.com/vtex-sites/nextjs.store/pull/242 accidentally introduced a Cumulative Layout Shift (CLS) of ~0.2 on the Home page. This PR returns the CLS to 0.
Thanks @tlgimenes for noticing this!
The CLS was introduced because the skeletons/placeholders weren't being used.
[Before](https://sfj-2d694d6--nextjs.preview.vtex.app/)|[After](https://sfj-328f8c8--nextjs.preview.vtex.app/)
-|-

fix: A regression with CLS on the Home page

---

src/server/index.ts

this pr resolves the type in the server file
the `execute` function takes two arguments `V` and `D` with V being the options and D being the context. However, V soon after is extracted into an object and the defined type did not foresee this causing the image below, so I add an extension to the V type so that it understands options as objects.
Checking if has ts any errors on file `src/server/index.ts`
TS Docs

fix: improve the execute server type

---

.storybook/storybook.css
src/components/sections/ProductDetails/product-details.module.scss
src/components/ui/ImageGallery/ImageGallery.stories.mdx
src/components/ui/ImageGallery/image-gallery.module.scss

Tiny PR to port some extra fixes we did on https://github.com/vtex-sites/gatsby.store/pull/205:
- Updates height values from `px` to `rem`
- Improves `ImageGallery` visibility on Storybook
- Fixes `ImageGallery` height on responsive views of the PDP
Check PDP page variants on both desktop and mobile views:
- [with gallery selector](https://sfj-6162459--nextjs.preview.vtex.app/apple-magic-mouse-99988212/p)
- [without gallery selector](https://sfj-6162459--nextjs.preview.vtex.app/4k-philips-monitor-99988213/p)
- [Storybook Doc](https://nextjs-store-storybook-git-fix-image-gallery-height-faststore.vercel.app/?path=/docs/organisms-imagegallery--default-story)
**PR …

fix: `ImageGallery` height on responsive views

---

package.json
src/components/common/Footer/footer.module.scss
src/components/common/Navbar/navbar.module.scss
src/components/product/OutOfStock/OutOfStock.tsx
src/components/product/OutOfStock/out-of-stock.module.scss
src/components/product/ProductCard/product-card.module.scss
src/components/search/Filter/Facets.tsx
src/components/search/SearchInput/search-input.module.scss
src/components/sections/Incentives/incentives.module.scss
src/components/sections/ProducDetailsContent/product-details-content.module.scss
src/components/sections/ProductDetails/product-details.module.scss
src/components/sections/ProductGallery/product-gallery.module.scss
src/components/ui/Alert/alert.module.scss
src/components/ui/Button/button.module.scss
src/components/ui/InputText/input-text.module.scss
src/components/ui/PriceRange/price-range.module.scss
src/components/ui/ProductTitle/product-title.module.scss
src/components/ui/QuantitySelector/quantity-selector.module.scss
src/components/ui/SROnly/SROnly.tsx
src/components/ui/SROnly/sr-only.scss
src/components/ui/SkuSelector/sku-selector.module.scss
yarn.lock

In order to use https://github.com/vtex/faststore/pull/1482 I decided to rename the `data-store` to `data-fs`.
All data-store attributes are renamed to data-fs.

fix: using data-fs instead data-store

---

src/components/common/Footer/Footer.stories.mdx
src/components/common/Footer/footer.module.scss
src/components/sections/Section/section.scss

Solves the scroll-locking behavior.
|Previous|After|
|-|-|
|https://user-images.githubusercontent.com/11325562/194408866-e7870691-8eb5-470d-a8a6-11fbdfa3ec80.mp4|![after](https://user-images.githubusercontent.com/11325562/194409860-036a1985-796a-48de-b067-aaad8b9ef244.gif)|
Removes the `content-visibility` related style from `section.scss` and `footer.scss`.
you can compare the preview link and the one from the https://nextjs.vtex.app/
https://web.dev/content-visibility/.
https://github.com/vtex-sites/base.store/pull/368

Feat: Removes content visibility

---

lighthouserc.js

This PR intends to change how Lighthouse treats the `resource-summary:stylesheet` metric (from error to warning). Also, the max numeric value for it was increased.
No code changes were applied.
- [Web.dev Resource summary](https://web.dev/resource-summary/)

chore: Change `resource-summary:stylesheet` metric to warning

---

cms/content-types.json
cms/sections.json
package.json
src/pages/index.tsx
src/server/cms.ts
store.config.js
yarn.lock

This PR does two things:
1. Add Newsletter component to CMS sections
2. Refactor Home to Page content type
`1` is pretty straight forward, however I still think this component should be refactored to be more CMS friendly (there are some texts that are not modifiable), but this can be done on a later PR
`2` will fulfill that vision that users may enter on the CMS, create a new "page" and configure a new institutional page, landing page etc. Turns out that the home page can be represented as one of those pages. 
Home content type was deleted and a Page was added. This new content type has a `settings` section where the user must enter infos like: `slug`, `title`, `description` and `canonical` page. If the canonical is not filled, it's inferred from store.config.json. The final CMS screen …

feat: Add Page content-type

---

package.json
yarn.lock

More info at: https://github.com/vtex/faststore/pull/1477
- Fix the search facets to use the productClusterIds when the pageType is Collection
- ❌ Navigate to page: [https://nextjs.vtex.app/just-arrived](https://nextjs.vtex.app/just-arrived) and you will see that it returns no search result
- ✅ Navigate to page: [https://sfj-2a1cff2--nextjs.preview.vtex.app/just-arrived](https://sfj-2a1cff2--nextjs.preview.vtex.app/just-arrived) and you will see that it works
<em>Spread the knowledge: is this any content you used to create this PR that is worth sharing?</em>

fix: collection pages facets

---

vtex.env

Configures site host for WebOps, so we serve this store at demo.faststore.dev

chore: Add site host

---

cms/content-types.json
cms/sections.json
src/components/cms/RenderPageSections.tsx
src/components/sections/CrossSellingShelf/CrossSellingShelf.tsx
src/components/sections/CrossSellingShelf/index.tsx
src/components/sections/ProductDetails/ProductDetails.tsx
src/pages/[slug]/p.tsx
src/pages/index.tsx
src/server/cms.ts
store.config.js

This PR is an RFC followed by an example implementation on how to  integrate the PDP with the CMS.  This implementation has several steps and some tradeoffs were made. I hope to clarify them in the next section
The first step was to create a new content type called PDP. This content type is supposed to be a singleton, this means there can only be one single instance of this content-type on the CMS. 
To render CMS sections, `RenderPageSections` is usually used. The issue in here is that components like `ProductDetails` expect the `product` data fetched on `getStaticProps`. To address this issue I had two possibilities, either add `product` info into a `React.Context` at `p.tsx` and use this context inside `ProductDetails`, or change `RenderPageSections` to pass additional props to section …

feat: Integrate CMS with PDP

---

package.json
yarn.lock

This PR changes package.json to specify the exact typescript version to be used. The `typescript` package is released in such a way that minor bumps can contain breaking changes. Defining it as `ˆ{version}` opens the possibility of yarn/npm installing a new minor version containing breaking changes, which can prevent the project (or projects that depends on `@faststore/core`) from being built.
This isn't a problem in this repo because `yarn.lock` locks the version on the one specified in package.json, but that doesn't happen when this package is installed by other projects.
This PR changes package.json to specify the exact typescript version to be used, removing the possibility of bumping minors and fixes automatically when the package is installed.
The store should be built and work as …

fix: specifies exact typescript version to avoid breaking changes

---

src/pages/[slug]/p.tsx

This PR is following another PR (https://github.com/vtex-sites/nextjs.store/pull/325) and fixes the custom components importing.
<em>Tell us the role of the new feature, or component, in its context.</em>

fix: custom components on pdp

---

src/customizations/components/index.ts
src/customizations/index.ts
src/pages/[slug]/p.tsx
src/pages/index.tsx

`faststore/cli` copies everything in the src folder, however, the home page tries to import the index from `src` and not from components, and this PR fixes that.
Just fix the import path.

fix: custom components on home page

---

package.json
tsconfig.json
yarn.lock

We don't need to use this configuration anymore, `@vtex/tsconfig` is deprecated.
<em>Tell us the role of the new feature, or component, in its context.</em>

chore: remove vtex tsconfig

---

package.json
src/components/cms/RenderPageSections.tsx
yarn.lock

When exists a Section on CMS, but the store doesn't have a component to render that, this log is shown:
```cmd
Could not find the component for block HelloWorld. Add a new component for this block or remove it from the CMS
Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
```
So, this PR improves this message and prevents key errors.
return null avoid fragment avoids the need to add key
<em>Extra tip: add references to related issues or mention people important to this PR may be good for the documentation and reviewing …

chore: improve log message when component not found in cms

---

src/pages/api/health.ts
src/pages/api/health/live.ts
src/pages/api/health/ready.ts

After @cezar-guimaraes request that we add a route to be used by the readiness probe. I **believe** the liveness probe should be on the nginx layer and therefore will be made in a separate PR.
An application endpoint that responds 200 (and the OK text) to whoever calls it.
Run the store and hit localhost:3000/api/health

Add an /api/health endpoint for readiness probe

---

package.json
src/components/search/Search.stories.mdx
src/components/search/SearchDropdown/SearchDropdown.stories.mdx
src/components/search/SearchInput/SearchInput.stories.mdx
src/components/search/SearchTop/SearchTop.stories.mdx
tsconfig.json
yarn.lock

Since this project is a dependency on the [starter.store](https://github.com/vtex-sites/starter.store/pull/12), we are getting a lot of errors while trying to build the evergreen commands over there.
[issue](https://github.com/vercel/next.js/issues/30182) and [workaround](https://github.com/vercel/next.js/issues/30182#issuecomment-965686256).
npm dependency compatibility ✅ 
This PR also attempts to fix this problem regarding MSW:

Fix: Evergreen `starter.store` build errors.

---

src/pages/[...slug].tsx
src/pages/[slug]/p.tsx

- It fixes the bug to reset pagination when navigating to another PLP
Adds key prop to identify the different PLP and PDP pages will reset the component tree’s state.
https://github.com/vtex-sites/nextjs.store/assets/3356699/39d2f633-5315-472b-9198-c04dbd424f84
1. In the `Office` category
2. Click in `Load more products`
3. Go to `Technology` category
4. You should be in the first page.
___ 
1. Go to any PDP;
2. Increase the product's quantity;
3. Click on any product inside the "People also bought" section".
4. The product's quantity should be 1.
Applied changes from this 2 PRs:
https://github.com/vtex/faststore/pull/2045
https://github.com/vtex/faststore/pull/2043

Fix: PLP reset pagination when navigating to another PLP
